name: deleteTEST
#yoppi
on:
  release:
  
jobs:
  delete_previous_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete Previous Release
        uses: cosmii02/delete-previous-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
