name: deleteTEST
#yoppi
on:
  push:
  pull_request:
  workflow_dispatch:
  

jobs:
  create_pre_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-candidate
          release_name: Release Candidate
          prerelease: true

  delete_previous_release:
    runs-on: ubuntu-latest
    needs: create_pre_release
    steps:
      - uses: actions/checkout@v2
      - name: Delete Previous Release
        uses: cosmii02/delete-previous-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
