name: Release Candidate

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Package
        run: dotnet dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained false -c Release --output ./forza/devrel
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ForzaDSX-RC
          path: ./forza/devrel
      - name: Delete Previous Release
        uses: cosmii02/delete-previous-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pre-Release
        id: create_release
        uses: cosmii02/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-candidate-${{ github.run_number }}-${{ github.run_id }}
          name: Release-Candidate-${{ github.run_number }}-${{ github.run_id }}
          prerelease: true
      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=id::$(echo '${{ steps.create_release.outputs.id }}')"
        shell: bash
      - name: Get Release Upload URL
        run: |
          echo "::set-output name=upload_url::$(curl -s -X GET -H \"Authorization: Bearer ${GITHUB_TOKEN}\" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${{ steps.create_release.outputs.tag }} | jq -r '.upload_url' | cut -d'{' -f1)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ForzaDSX-RC
          path: ./forza/devrel
          url: ${{ steps.get_release_upload_url.outputs.upload_url }}
